import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Web Component with App Router</title>
            {/* Web Component 스크립트 로드 */}
            <Script src="/components/MyButton.js" type="module" strategy='lazyOnload' ></Script>
        </head>
        <body>
        <header>
            <h1>My App</h1>
        </header>
        <main>{children}</main>
        <footer>© 2024 My App</footer>
        </body>
        </html>
    );
}
